services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40000:80"
    volumes:
      - ./src/cdn/:/var/www/html/cdn/
      - ./src/server-emulator/:/server-emulator/
      - ./src/web/index.html:/var/www/html/index.html
